services:
  api:
    container_name: libra-net-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5500:80
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings__Default=${CONNECTION_STRINGS_DEFAULT}"
      - "Settings__Admin__Email=${SETTINGS_ADMIN_EMAIL}"
      - "Settings__Admin__Password=${SETTINGS_ADMIN_PASSWORD}"
      - "Settings__Password__AdditionalKey=${SETTINGS_PASSWORD_ADDITIONAL_KEY}"
      - "Settings__Jwt__ExpirationTimeMinutes=${SETTINGS_JWT_EXPIRATION_TIME_MINUTES}"
      - "Settings__Jwt__SigningKey=${SETTINGS_JWT_SIGNING_KEY}"
    depends_on: ["libra-net-postgres"]
    networks:
      libra-net-networks:

  libra-net-postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    volumes:
      - "libra-net-pg:/var/lib/postgresql/data"
    networks:
      libra-net-networks:
        aliases:
          - "host"
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: libra-net-pgadmin
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"
    depends_on: ["libra-net-postgres"]
    networks:
      - libra-net-networks

volumes:
  libra-net-pg:

networks:
  libra-net-networks:
    driver: bridge
